In [1]:
import numpy as np
np.zeros((10,2,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [2]:
np.ones((10,2,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [3]:
np.random.randn(3,3,5)

array([[[-0.47803629,  0.55481354,  1.08457913,  1.27358715,
          1.76757634],
        [ 2.34493659,  0.01690253, -1.72173788,  0.4791954 ,
         -0.1932786 ],
        [ 0.36803346, -0.28061846, -0.99029712, -0.39971491,
         -1.04693568]],

       [[ 0.15849812, -0.7282423 ,  0.54666896,  0.97099939,
          0.10598494],
        [ 0.31854898,  0.04366498, -1.77864359, -1.90901435,
          0.40632227],
        [ 0.19739824, -1.23790091, -0.04894815,  0.01709123,
          1.8025349 ]],

       [[ 0.29488389, -1.18364748,  0.5857804 ,  1.96406395,
          0.18805891],
        [-0.04260142, -1.34118019,  0.15040134, -0.61295603,
         -0.83708402],
        [-2.14304538, -0.19984904,  0.88879268,  0.26087764,
          1.73894312]]])

In [4]:
np.arange(101)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [5]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

**Comparison between normal list and arange **

In [6]:
import time
iterations=100000000
before=time.time()
list(range(iterations))
after=time.time()
python_time=after-before
print(f'Python time: {python_time}')

before=time.time()
np.arange(iterations)
after=time.time()
numpy_time=after-before
print(f'Numpy time: {numpy_time}')
print(f'Numpy is {python_time/numpy_time} times faster')


Python time: 13.394395112991333
Numpy time: 0.2134561538696289
Numpy is 62.7501005249637 times faster


In [7]:
arr1=np.array([1,6,7,9,1,8,3,7])
np.sort(arr1)

array([1, 1, 3, 6, 7, 7, 8, 9])

In [8]:
a=np.array([4,6,8,9])
b=np.array([7,6,2,9])
np.concatenate((a,b))

array([4, 6, 8, 9, 7, 6, 2, 9])

In [9]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
a.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

Create an array óf 64 elements (64,) and reshape into
(16,4),(4,4,4),(8,2,4),(10,2)

In [11]:
a=[1,2,3,4,5]
a*5

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [12]:
data=np.array([1,2,3,4,5,])
data*20

array([ 20,  40,  60,  80, 100])

It was the difference between list and numpy array

In [13]:
 data.max()

5

In [14]:
 data.min()

1

In [16]:
 data.sum()

15

Exercise: Double each  list element
i.e [10,12,14,16]=[5,6,7,8]

using normal python approach
using numpy apporach

In [21]:

#using python approach
numbers=[10,12,14,16]
new_numbers=[]
for number in numbers:
    new_numbers.append(number/2.0)
print(new_numbers)

[5.0, 6.0, 7.0, 8.0]


In [27]:
#using numpy approach
numbers=np.array([10,12,14,16])
divided_numbers=numbers/2
divided_numbers=a
a

[1, 2, 3, 4, 5]

In [28]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [29]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [30]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

In [32]:
a=np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
a[(a>6) & (a<14)]

array([ 7,  8,  9, 10, 11, 12, 13])

!Create two np arrays random numbers

1)Array A should have dimension 2,3

2)Array B should have dimension 3,2

In [35]:
a=np.random.randn(2,3)
b=np.random.randn(3,2)

In [36]:
a

array([[-1.23088508,  1.26499676,  1.47197303],
       [ 0.50127693, -0.00400181, -0.09662103]])

In [37]:
b

array([[ 0.9223856 , -0.95541239],
       [-1.38148747,  0.25337523],
       [ 0.34095579, -0.13909192]])

In [38]:
np.matmul(a,b)

array([[-2.38105013,  1.29178215],
       [ 0.43495558, -0.46650095]])

Create a random matrix of shape(1000,3) and create another with a shape(3,1000) .

Chech the shape of the resultant matrix after multiplication

In [39]:
a=np.random.randn(1000,3)
b=np.random.randn(3,1000)

In [40]:
a

array([[-0.41810441, -0.30506   , -1.4461145 ],
       [ 0.66507857, -0.83280626, -0.55878151],
       [-0.24437414,  1.44298315,  0.00991975],
       ...,
       [ 0.07378903, -2.06591635, -2.78903419],
       [ 0.60623356,  1.82200515,  0.76075836],
       [ 0.59746966, -1.94235417, -0.47931682]])

cREATE A numpy array of range 10 Reshape it to (5,2) .What is the transpose of (5,2)

In [41]:
 arr=np.arange(10)
 arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arr.reshape(5,2)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
arr.T

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Create an array of 64 elements (64,) and reshape into

(16,4)
(4,4,4)
(8,2,4)
(10,2)

Divisible by two

Create a numpy array from 1 to 50
Filter only even elements by passing the condition as index.

Greater than and less than?

In [55]:
array_64=np.arange(1,65)
array_64

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

In [56]:
reshape_16_4=arra

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32],
       [33, 34, 35, 36],
       [37, 38, 39, 40],
       [41, 42, 43, 44],
       [45, 46, 47, 48],
       [49, 50, 51, 52],
       [53, 54, 55, 56],
       [57, 58, 59, 60],
       [61, 62, 63, 64]])

In [57]:
reshape_4_4_4=np.reshape(array_64,(4,4,4))
reshape_4_4_4
#

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]],

       [[33, 34, 35, 36],
        [37, 38, 39, 40],
        [41, 42, 43, 44],
        [45, 46, 47, 48]],

       [[49, 50, 51, 52],
        [53, 54, 55, 56],
        [57, 58, 59, 60],
        [61, 62, 63, 64]]])

Create an array from 1 to 50, filter only even elements, and apply conditions to find elements greater than and less than certain values.


In [58]:
array_1_50=np.arange(1,51)
array_1_50

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [59]:
array_elements=array_1_50[array_1_50%2==0]
array_elements

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

In [60]:
filter_elements=array_1_50[(array_1_50<10) & (array_1_50>5)]
filter_elements

array([6, 7, 8, 9])

In [61]:
import numpy as np

# Create an array of 64 elements
array_64 = np.arange(1, 65)  # Numbers from 1 to 64

# Reshaping the array into different shapes
reshape_16_4 = array_64.reshape(16, 4)
reshape_4_4_4 = array_64.reshape(4, 4, 4)
reshape_8_2_4 = array_64.reshape(8, 2, 4)
reshape_10_2 = array_64[:20].reshape(10, 2)  # First 20 elements reshaped into (10, 2)

# Display the reshaped arrays
print("Shape (16, 4):\n", reshape_16_4)
print("\nShape (4, 4, 4):\n", reshape_4_4_4)
print("\nShape (8, 2, 4):\n", reshape_8_2_4)
print("\nShape (10, 2):\n", reshape_10_2)

# Create an array from 1 to 50
array_1_to_50 = np.arange(1, 51)

# Filter only even elements
even_elements = array_1_to_50[array_1_to_50 % 2 == 0]

print("\nEven elements from 1 to 50:", even_elements)

# Filter elements greater than 10 and less than 40
filtered_elements = array_1_to_50[(array_1_to_50 > 10) & (array_1_to_50 < 40)]

print("\nElements greater than 10 and less than 40:", filtered_elements)


Shape (16, 4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]
 [33 34 35 36]
 [37 38 39 40]
 [41 42 43 44]
 [45 46 47 48]
 [49 50 51 52]
 [53 54 55 56]
 [57 58 59 60]
 [61 62 63 64]]

Shape (4, 4, 4):
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]]

 [[33 34 35 36]
  [37 38 39 40]
  [41 42 43 44]
  [45 46 47 48]]

 [[49 50 51 52]
  [53 54 55 56]
  [57 58 59 60]
  [61 62 63 64]]]

Shape (8, 2, 4):
 [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]]

 [[33 34 35 36]
  [37 38 39 40]]

 [[41 42 43 44]
  [45 46 47 48]]

 [[49 50 51 52]
  [53 54 55 56]]

 [[57 58 59 60]
  [61 62 63 64]]]

Shape (10, 2):
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]

Even elements from 1 to 50: [ 2  4  6  8 10 12 14 16 18 20 2

Numpy Exercises
Multiply the following two NumPy arrays element-wise: [1, 2, 3] and [4, 5, 6], and print the result.

Calculate the mean of the following NumPy array: [3, 7, 10, 15, 19], and print the result.

Reshape the following NumPy array into a 2x3 matrix: [1, 2, 3, 4, 5, 6].
Find the maximum value in the following NumPy array: [9, 2, 7, 5, 3], and print it.

More exercises

Create a 2D NumPy array with shape (5, 5) containing random integers between 1 and 100. Replace all values greater than 50 with 0 and print the modified array.

Create a 1D NumPy array with 20 elements ranging from 0 to 100. Reshape the array into a 4x5 matrix and print it.

Create a 3x3 matrix with random values between 0 and 1. Replace all values less than 0.5 with 0 and print the modified matrix.

Create a 1D NumPy array with 100 elements ranging from 1 to 100. Reshape the array into a 10x10 matrix and calculate the sum of each row. Print the sum.

Create a 2D NumPy array with shape (4, 4) containing random integers between 1 and 10. Find the indices of the maximum value in each row and print the indices.

Create a 1D NumPy array with 50 random elements randomly. Calculate the mean and standard deviation of the array and print the results.

Create a 2D NumPy array with shape (3, 3) and fill it with values ranging from 0 to 8. Shuffle the rows randomly and print the shuffled array.

Create a 1D NumPy array with 100 elements ranging from 1 to 10. Replace all odd values with -1 and print the modified array.

Create a 3x3 matrix with random values between 0 and 1. Normalize the matrix by dividing each row by the sum of its elements and print the normalized matrix.

Create a 2D NumPy array with shape (5, 5) and fill it with random values between 0 and 1. Sort the elements in each column in descending order and print the sorted array.

# Numpy Exercises Multiply the following two NumPy arrays element-wise: [1, 2, 3] and [4, 5, 6], and print the result.

# Calculate the mean of the following NumPy array: [3, 7, 10, 15, 19], and print the result.

# Reshape the following NumPy array into a 2x3 matrix: [1, 2, 3, 4, 5, 6]. Find the maximum value in the following NumPy array: [9, 2, 7, 5, 3], and print it.

In [70]:
a=np.array([1,2,3])
b=np.array([4,5,6])
result=a*b
print(f"Element wise result is {result}")

Element wise result is [ 4 10 18]


In [73]:
mean_array=np.array([3,7,10,15,19])
mean=np.mean(mean_array)
print(f"The mean of the array is {mean}")

The mean of the array is 10.8


In [75]:
reshape_matrix=np.array([1,2,3,4,5,6])
result=reshape_matrix.reshape(2,3)
result

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
find_max=np.array([9,2,7,5,3])
max=np.max(find_max)
max

9

Create a 2D NumPy array with shape (5, 5) containing random integers between 1 and 100. Replace all values greater than 50 with 0 and print the modified array.

Create a 1D NumPy array with 20 elements ranging from 0 to 100. Reshape the array into a 4x5 matrix and print it.

Create a 3x3 matrix with random values between 0 and 1. Replace all values less than 0.5 with 0 and print the modified matrix.

Create a 1D NumPy array with 100 elements ranging from 1 to 100. Reshape the array into a 10x10 matrix and calculate the sum of each row. Print the sum.

In [90]:
import numpy as np

# Create a 2D array of random integers between 1 and 100
array_2d = np.random.randint(1, 101, size=(5, 5))

array_2d



array([[19, 63, 32, 33, 51],
       [36, 60, 27, 59, 50],
       [96, 96, 92, 93, 58],
       [87, 64, 71, 58, 87],
       [66, 10, 95,  4, 28]])

In [91]:
# Replace all values greater than 50 with 0
array_2d[array_2d > 50] = 0

print("Modified array with values > 50 replaced by 0:\n", array_2d)

Modified array with values > 50 replaced by 0:
 [[19  0 32 33  0]
 [36  0 27  0 50]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0 10  0  4 28]]


Create a 1D NumPy array with 20 elements ranging from 0 to 100. Reshape the array into a 4x5 matrix and print it.

In [93]:
# Create a 1D arrayint)
 of 20 elements ranging from 0 to 100
array_1d = np.linspace(0, 100, 20, dtype=
# Reshape into a 4x5 matrix
reshaped_matrix = array_1d.reshape(4, 5)

print("Reshaped 4x5 matrix:\n", reshaped_matrix)


Reshaped 4x5 matrix:
 [[  0   5  10  15  21]
 [ 26  31  36  42  47]
 [ 52  57  63  68  73]
 [ 78  84  89  94 100]]


 Create a 3x3 matrix with random values between 0 and 1, replace values less than 0.5 with 0:

In [95]:
matrix_33=np.random.rand(3,3)
matrix_33

array([[0.71781424, 0.64245172, 0.88170482],
       [0.60087091, 0.80736822, 0.11542134],
       [0.94339386, 0.33064964, 0.59657444]])

In [98]:
matrix_33[matrix_33<0.643]=0
matrix_33

array([[0.71781424, 0.        , 0.88170482],
       [0.        , 0.80736822, 0.        ],
       [0.94339386, 0.        , 0.        ]])

Create a 1D NumPy array with 100 elements ranging from 1 to 100, reshape into a 10x10 matrix, and calculate the sum of each row:

In [103]:
arr_1d=np.arange(1,101)
arr_1d

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [105]:
reshaped_matrix=arr_1d.reshape(10,10)
reshaped_matrix

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [110]:
#how to calculate the sum of each row ??
row_sum=np.sum(reshaped_matrix,axis=1)
print("10x10 matrix:\n", arr_1d)
print("\nSum of each row:", row_sum)

10x10 matrix:
 [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]

Sum of each row: [ 55 155 255 355 455 555 655 755 855 955]


Create a 2D NumPy array with shape (4, 4) containing random integers between 1 and 10. Find the indices of the maximum value in each row and print the indices.

Create a 1D NumPy array with 50 random elements randomly. Calculate the mean and standard deviation of the array and print the results.

Create a 2D NumPy array with shape (3, 3) and fill it with values ranging from 0 to 8. Shuffle the rows randomly and print the shuffled array.

Create a 1D NumPy array with 100 elements ranging from 1 to 10. Replace all odd values with -1 and print the modified array.

Create a 3x3 matrix with random values between 0 and 1. Normalize the matrix by dividing each row by the sum of its elements and print the normalized matrix.

Create a 2D NumPy array with shape (5, 5) and fill it with random values between 0 and 1. Sort the elements in each column in descending order and print the sorted array.

In [ ]:
#This much of questions to do but i am feeling bored !Sorry thank u