In [2]:
import pandas as pd
from sklearn.datasets import load_breast_cancer

cancer_data=load_breast_cancer()
cancer_data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [3]:
#feature
#target

*data

*target

*target_names

*Feature_names

In [4]:
cancer_data['data']

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [6]:
 cancer_data['data'].shape

(569, 30)

In [7]:
cancer_data['data'][0]

array([1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
       3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
       8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
       3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
       1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01])

In [8]:
import numpy as np


In [9]:
a=np.array([1,2,3,4,5])

In [10]:
a

array([1, 2, 3, 4, 5])

In [11]:
type(a)

numpy.ndarray

In [12]:
a.ndim

1

In [17]:
b=np.array([[1,2,3,4,5,6,7],[1,2,3,4,5,7,6]])
b


array([[1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 7, 6]])

In [18]:
b.ndim

2

In [19]:
b.shape


(2, 7)

In [21]:
arr = np.array(
    [[[[[[1, 2, 3, 4], [5, 6, 8, 9], [9, 10, 11, 12]],
    [[1, 9, 3, 4], [5, 7, 8, 9], [9, 10, 11, 12]]],
    [[[1, 2, 3, 4], [5, 6, 8, 9], [9, 10, 11, 12]],
    [[1, 9, 3, 4], [5, 7, 8, 9], [9, 10, 11, 12]]]],
    [[[[1, 2, 3, 4], [5, 6, 8, 9], [9, 10, 11, 12]],
    [[1, 9, 3, 4], [5, 7, 8, 9], [9, 10, 11, 12]]],
    [[[1, 2, 3, 4], [5, 6, 8, 9], [9, 10, 11, 12]],
    [[1, 9, 3, 4], [5, 7, 8, 9999], [9, 10, 11, 12]]]]],
    [[[[[1, 2, 3, 4], [5, 6, 8, 9], [9, 10, 11, 12]],
    [[1, 9, 3, 4], [5, 7, 8, 9], [9, 10, 11, 12]]],
    [[[1, 2, 3, 4], [5, 6, 8, 9], [9, 10, 11, 12]],
    [[1, 9, 3, 4], [5, 7, 8, 9], [9, 10, 11, 12]]]],
    [[[[1, 2, 3, 4], [5, 6, 8, 9], [9, 10, 11, 12]],
    [[1, 9, 3, 4], [5, 7, 8, 9], [9, 10, 11, 12]]],
    [[[1, 2, 3, 4], [5, 6, 8, 9], [9, 10, 11, 12]],
    [[1, 9, 3, 4], [5, 7, 8, 9], [9, 10, 11, 12]]]]]]
)

In [22]:
arr.ndim

6

In [23]:
arr.shape

(2, 2, 2, 2, 3, 4)

In [26]:
location=np.where(arr==9999)
location

(array([0]), array([1]), array([1]), array([1]), array([1]), array([3]))