In [2]:
import numpy as np
np.zeros((10,2,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [3]:
np.ones((10,2,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [4]:
np.random.randn(3,3,5)

array([[[-1.28269958,  0.26096963, -0.56216618,  0.36036644,
          0.13447631],
        [ 0.13801817,  0.38208749, -0.05715406,  0.39023987,
         -0.00699657],
        [ 0.01524319,  1.06721435,  0.62200301,  0.20611389,
          1.29121598]],

       [[ 0.66363096,  1.25454844, -0.27817157,  1.62657789,
          2.64868595],
        [-0.69392714,  0.11307451, -0.21713335, -1.26721184,
          2.13846702],
        [ 1.36657011, -1.22104663, -0.30418177, -0.49122869,
          0.43785726]],

       [[-2.3987113 , -0.12061447, -1.12575331, -1.15838142,
          0.57090367],
        [ 2.74314811,  0.22156911,  0.64253689, -1.90267929,
         -0.13814263],
        [-0.4160976 , -0.5626976 ,  0.39773179, -1.83289935,
         -1.37773837]]])

In [6]:
np.arange(101)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [7]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

**Comparison between normal list and arange **

In [11]:
import time
iterations=100000000
before=time.time()
list(range(iterations))
after=time.time()
python_time=after-before
print(f'Python time: {python_time}')

before=time.time()
np.arange(iterations)
after=time.time()
numpy_time=after-before
print(f'Numpy time: {numpy_time}')
print(f'Numpy is {python_time/numpy_time} times faster')


Python time: 5.240652799606323
Numpy time: 0.36687183380126953
Numpy is 14.284696498246653 times faster


In [17]:
arr1=np.array([1,6,7,9,1,8,3,7])
np.sort(arr1)

array([1, 1, 3, 6, 7, 7, 8, 9])

In [18]:
a=np.array([4,6,8,9])
b=np.array([7,6,2,9])
np.concatenate((a,b))

array([4, 6, 8, 9, 7, 6, 2, 9])

In [21]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
a.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])