In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB

In [ ]:
from sklearn.datasets import load_digits

In [ ]:
digits=load_digits()

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.2)

In [ ]:
lr=LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9638888888888889

In [ ]:
svm=SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9861111111111112

In [ ]:
rf=RandomForestClassifier()
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9694444444444444

In [ ]:
from sklearn.linear_model import LinearRegression
lir=LinearRegression()
lir.fit(X_train,y_train)
lir.score(X_test,y_test)

0.5568485610191564

In [ ]:
from sklearn.model_selection import KFold

In [ ]:
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [ ]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
  print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [ ]:
def get_score(model,X_train,X_test,y_train,y_test):
  model.fit(X_train,y_train)
  return model.score(X_test,y_test)

In [ ]:
get_score(LinearRegression(),X_train,X_test,y_train,y_test)

0.5568485610191564

In [ ]:
get_score(SVC(),X_train,X_test,y_train,y_test)

0.9861111111111112

In [ ]:
get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test)

0.9583333333333334

In [ ]:
from sklearn.model_selection import  StratifiedKFold

In [ ]:
folds=StratifiedKFold(n_splits=3)

In [ ]:
from sklearn.model_selection import KFold
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

# Assuming you have the digits dataset loaded (e.g., from sklearn.datasets)

# Create a KFold object with the desired number of splits
kf = KFold(n_splits=3, shuffle=True, random_state=42)

# Initialize lists to store scores for each model
scores_lr = []
scores_svm = []
scores_rf = []

# Function to get the model score
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

# Iterate through the folds
for train_index, test_index in kf.split(digits.data):
    X_train, X_test = digits.data[train_index], digits.data[test_index]
    y_train, y_test = digits.target[train_index], digits.target[test_index]

    scores_lr.append(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))

# Print the scores for each model
print("Logistic Regression Scores:", scores_lr)
print("SVM Scores:", scores_svm)
print("Random Forest Scores:", scores_rf)

# Calculate and print the average score for each model
avg_lr = sum(scores_lr) / len(scores_lr)
avg_svm = sum(scores_svm) / len(scores_svm)
avg_rf = sum(scores_rf) / len(scores_rf)

print("Average Logistic Regression Score:", avg_lr)
print("Average SVM Score:", avg_svm)
print("Average Random Forest Score:", avg_rf)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

Logistic Regression Scores: [0.9649415692821369, 0.9649415692821369, 0.9532554257095158]
SVM Scores: [0.986644407345576, 0.988313856427379, 0.986644407345576]
Random Forest Scores: [0.9682804674457429, 0.9632721202003339, 0.9749582637729549]
Average Logistic Regression Score: 0.9610461880912632
Average SVM Score: 0.9872008903728436
Average Random Forest Score: 0.9688369504730105


In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [ ]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [ ]:
cross_val_score(RandomForestClassifier(n_estimators=30),digits.data,digits.target)

array([0.91666667, 0.90277778, 0.95264624, 0.95821727, 0.89693593])

In [ ]:
cross_val_score(RandomForestClassifier(n_estimators=50),digits.data,digits.target)

array([0.92777778, 0.90277778, 0.95543175, 0.9637883 , 0.91922006])