 <span style="font-family: 'Arial'; font-size: 24px; font-weight: bold; background-color: yellow; color: black; padding: 5px;">Bag of Words (BoW) is a simple and widely used technique in natural language processing (NLP) and machine learning for converting text data (like sentences or documents) into numerical features.</span>

In [1]:
import pandas as pd 
import numpy as np 


In [5]:
df=pd.DataFrame({'text':['people watch campusx','campusx watch campusx','people write comment','campusx write comment'],'output':[1,1,0,0]})

In [6]:
df

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [16]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [17]:
print(df['text'].head())
print(df['text'].dtype)


0     people watch campusx
1    campusx watch campusx
2     people write comment
3    campusx write comment
Name: text, dtype: object
object


In [18]:
bow= cv.fit_transform(df['text'])

In [19]:
bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 11 stored elements and shape (4, 5)>

In [20]:
print(bow[0].toarray())

[[1 0 1 1 0]]


In [21]:
print(bow[3].toarray())

[[1 1 0 0 1]]


In [25]:
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


In [27]:
print(bow[1].toarray())


[[2 0 0 1 0]]


 <span style="font-family: 'Arial'; font-size: 24px; font-weight: bold; background-color: yellow; color: black; padding: 5px;">Bag Of Biagrams </span>

In [30]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(ngram_range=(2,2))

In [31]:
bow1=cv.fit_transform(df['text'])

In [33]:
bow1

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 8 stored elements and shape (4, 6)>

In [34]:
print(cv.vocabulary_)

{'people watch': 2, 'watch campusx': 4, 'campusx watch': 0, 'people write': 3, 'write comment': 5, 'campusx write': 1}


In [35]:
print(bow1[0].toarray())

[[0 0 1 0 1 0]]


In [36]:
print(bow1[2].toarray())

[[0 0 0 1 0 1]]


 <span style="font-family: 'Arial'; font-size: 24px; font-weight: bold; background-color: yellow; color: black; padding: 5px;">Bag Of Triagrams
 </span>

In [39]:
cv=CountVectorizer(ngram_range=(3,3))
bow3=cv.fit_transform(df['text'])

In [40]:
print(cv.vocabulary_)

{'people watch campusx': 2, 'campusx watch campusx': 0, 'people write comment': 3, 'campusx write comment': 1}
