*************Welcome to Numpy Tutorial********************* 

In [13]:
import numpy as np

In [14]:
arr=np.array([[2,4,87,44]],np.int32)

In [15]:

arr = np.array([[2, 45, 6, 89, 4]], np.int32)
print(arr)


[[ 2 45  6 89  4]]


In [16]:
arr[0]

array([ 2, 45,  6, 89,  4], dtype=int32)

In [17]:
arr[0,1]

np.int32(45)

In [18]:
arr[0,2]

np.int32(6)

In [19]:
arr.shape

(1, 5)

In [20]:
arr[0,1]=45

In [21]:
arr

array([[ 2, 45,  6, 89,  4]], dtype=int32)

In [22]:
listarray=np.array([[1,23,4],[56,43,78],[1,2,3]])

In [23]:
#array creation : Conversion from other python arrays 


In [24]:
listarray

array([[ 1, 23,  4],
       [56, 43, 78],
       [ 1,  2,  3]])

In [25]:
listarray.dtype

dtype('int64')

In [26]:
listarray.shape

(3, 3)

In [27]:
listarray.size

9

In [28]:
np.array({2,34,5})

array({2, 34, 5}, dtype=object)

In [29]:
import numpy as np


In [39]:
ary=np.array([[2,17,12],[5,6,8],[12,15,3]])

In [40]:
ary.shape

(3, 3)

In [41]:
ary.size

9

In [43]:
ary.sum(axis=0)

array([19, 38, 23])

In [44]:
ary.sum(axis=1)

array([31, 19, 30])

In [48]:
ary.flat

In [49]:
for element in ary.flat:
    print(element)

2
17
12
5
6
8
12
15
3


In [50]:
ary.ndim

2

In [52]:
ary.size

9

In [53]:
ary.nbytes

72

In [59]:
one=np.array([3,45,67,12,9])

In [60]:
one.argmax()

np.int64(2)

In [62]:
one.argmin()

np.int64(0)

In [63]:
one.argsort()

array([0, 4, 3, 1, 2])

In [64]:
ary

array([[ 2, 17, 12],
       [ 5,  6,  8],
       [12, 15,  3]])

In [67]:
ary.argmax()

np.int64(2)

In [68]:
ary.argmax(axis=0)

array([1, 0, 0])

In [69]:
ary.argmax(axis=1)

array([2, 2, 2])

In [72]:
ar2=np.array([[23,1,15],[3,7,9],[0,4,27]])

In [73]:
ary+ar2

array([[25, 13, 32],
       [ 8, 13, 17],
       [ 3, 16, 42]])

In [75]:
np.sqrt(ar2)

array([[4.79583152, 1.        , 3.87298335],
       [1.73205081, 2.64575131, 3.        ],
       [0.        , 2.        , 5.19615242]])

In [76]:
ar2.max()

np.int64(27)

In [77]:
ar2.min()

np.int64(0)

In [78]:
ar2.sort()

In [80]:
np.where(ar2>5)

(array([0, 0, 1, 1, 2]), array([1, 2, 1, 2, 2]))

In [81]:
np.nonzero(ary)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [82]:
import sys

In [83]:
py_arr=[1,23,12]

In [85]:
np_arr=np.array(py_arr)

In [86]:
np_arr.size

3

In [91]:
sys.getsizeof(1)* len(py_arr)

84