In [6]:
import numpy as np 
import cv2

In [ ]:
import cv2
import numpy as np  # Ensure numpy is imported for corner handling

# Read the image
img = cv2.imread('Chessboard.png')

# Resize the image
img = cv2.resize(img, (0, 0), fx=0.75, fy=0.75)

# Convert the image to grayscale
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Detect corners using goodFeaturesToTrack
corners = cv2.goodFeaturesToTrack(img_gray, 100, 0.01, 10)

# Draw the corners on the image
if corners is not None:
    corners = np.int0(corners)  # Convert corners to integer type
    for corner in corners:
        x, y = corner.ravel()  #Flatten an array
        cv2.circle(img, (x, y), 5, (0, 255, 0), -1)  # Draw a circle at each corner

# Display the image with corners
cv2.imshow('Frame', img)
cv2.waitKey(0)  # Wait for a key press
cv2.destroyAllWindows()  # Close all OpenCV windows

C:\Users\Nitro\AppData\Local\Temp\ipykernel_13324\3933438003.py:18: DeprecationWarning: `np.int0` is a deprecated alias for `np.intp`.  (Deprecated NumPy 1.24)
  corners = np.int0(corners)  # Convert corners to integer type


In [14]:
print(corners)

[[[225 225]]

 [[383 225]]

 [[ 66 224]]

 [[225 383]]

 [[224  66]]

 [[225 330]]

 [[330 225]]

 [[119 225]]

 [[225 119]]

 [[225 277]]

 [[224 172]]

 [[277 225]]

 [[172 224]]

 [[382 382]]

 [[ 67  67]]

 [[ 67 383]]

 [[382  66]]

 [[329 329]]

 [[120 120]]

 [[120 329]]

 [[329 120]]

 [[278 329]]

 [[171 120]]

 [[329 278]]

 [[120 171]]

 [[171 329]]

 [[278 120]]

 [[120 278]]

 [[329 171]]

 [[383 330]]

 [[ 66 119]]

 [[330 383]]

 [[119  66]]

 [[ 66 330]]

 [[383 119]]

 [[119 383]]

 [[330  66]]

 [[278 278]]

 [[171 171]]

 [[171 278]]

 [[278 171]]

 [[ 66 277]]

 [[383 172]]

 [[383 277]]

 [[ 66 172]]

 [[277 383]]

 [[172  66]]

 [[172 383]]

 [[277  66]]

 [[446 446]]

 [[  3 446]]

 [[446   3]]

 [[  3   3]]

 [[435 225]]

 [[ 14 224]]

 [[225 435]]

 [[224  14]]

 [[ 14 435]]

 [[435  14]]

 [[ 14 383]]

 [[435  66]]

 [[ 66 435]]

 [[383  14]]

 [[382 435]]

 [[ 67  14]]

 [[435 382]]

 [[ 14  67]]

 [[ 14 330]]

 [[435 119]]

 [[435 330]]

 [[ 14 119]]

 [[330